apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat-container
        image: ahmetcan114/chat:latest
        ports:
        - containerPort: 8080
