# Yeni cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccountName }}
          containers:
          - name: {{ .Values.name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: OPSGENIE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opsgenie-secret
                  key: opsgenieApiKey
            - name: SCHEDULE_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: schedule-secret
                  key: scheduleIdentifier
            - name: GOOGLE_CHAT_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: google-chat-secret
                  key: googleChatWebhookUrl
          restartPolicy: OnFailure
