# chat-bot/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: chat-bot-cronjob
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  successfulJobsHistoryLimit: "{{ .Values.cronJob.successfulJobsHistoryLimit }}"
  failedJobsHistoryLimit: "{{ .Values.cronJob.failedJobsHistoryLimit }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: chat-bot
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: "{{ .Values.image.pullPolicy }}"
            env:
              - name: OPSGENIE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: opsgenie-secret
                    key: opsgenieApiKey
              - name: SCHEDULE_IDENTIFIER
                valueFrom:
                  secretKeyRef:
                    name: schedule-secret
                    key: scheduleIdentifier
              - name: GOOGLE_CHAT_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: google-chat-secret
                    key: googleChatWebhookUrl
          restartPolicy: "{{ .Values.cronJob.restartPolicy }}"
